# Site settings
title: Ty Warren
description: A blog about programming and gaming
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://punkty.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ty Warren
user_description: Hi! My name is Ty, I am software developer with an emphasis in web and iOS applications. 
user_title: Software Developer
email: iamtylerwarren@gmail.com
twitter_username: TySoftwaredev
github_username:  punkty
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
